import type {
  GovernanceDashboardMockContract,
  GovernanceDashboardReadOnlyData,
  GovernanceProjectionIntegrity,
  GovernanceProjectionIntegrityLevel,
  GovernanceProjectionId,
  GovernanceProjectionLineage,
} from "./governanceDashboardTypes";

const parentTraceId = "mock-parent-trace-governance-dashboard";

function createGovernanceProjectionLineage({
  projectionId,
  parentProjectionId = "root",
  derivedFrom = [],
  dependencies = [],
}: {
  readonly projectionId: GovernanceProjectionId;
  readonly parentProjectionId?: GovernanceProjectionId | "root";
  readonly derivedFrom?: readonly GovernanceProjectionId[];
  readonly dependencies?: readonly GovernanceProjectionId[];
}): GovernanceProjectionLineage {
  return {
    parent: {
      parentProjectionId,
      label: parentProjectionId === "root" ? "root ガバナンス表示モデル" : "親表示モデル",
      semanticMeaning: "参照のみの由来(lineage)親であり、表示モデル(projection)再生成や実行順序ではありません。",
    },
    derivedFrom: derivedFrom.map((sourceProjectionId) => ({
      sourceProjectionId,
      label: "由来となる説明 source",
      semanticMeaning: "説明文脈(reasoning context)の由来であり、source mutation ではありません。",
    })),
    dependencies: dependencies.map((dependencyProjectionId) => ({
      dependencyProjectionId,
      label: "参照のみの説明依存関係",
      semanticMeaning: "表示上の説明依存関係(reasoning dependency)であり、実行依存ではありません。",
    })),
    trace: {
      traceId: `${projectionId}:trace`,
      parentTraceId,
      requestChainLabel: "静的ガバナンス確認 parent trace",
    },
  };
}

function createGovernanceProjectionIntegrity({
  level,
  issueLabels = [],
  signalLabels = [],
}: {
  readonly level: GovernanceProjectionIntegrityLevel;
  readonly issueLabels?: readonly string[];
  readonly signalLabels?: readonly string[];
}): GovernanceProjectionIntegrity {
  return {
    level,
    issues: issueLabels.map((label, index) => ({
      issueId: `integrity-issue-${level}-${index + 1}`,
      level,
      label,
      semanticMeaning: "整合性確認(integrity review)の表示であり、修復や再生成の開始ではありません。",
    })),
    signals: signalLabels.map((label, index) => ({
      signalId: `integrity-signal-${level}-${index + 1}`,
      level,
      label,
      semanticMeaning: "ガバナンス整合性(governance integrity)の確認シグナルであり、mutation を意味しません。",
    })),
    summaryLabel: `整合性: ${level}`,
  };
}

const governanceDashboardMockData: GovernanceDashboardMockContract = {
  renderingState: {
    renderState: "readonly",
    freshnessState: "fresh",
    degradationState: "limited",
    visibilityMode: "overview",
    label: "参照のみの描画状態",
    message:
      "静的 mock data を参照のみの描画として表示しています。一部表示(partial) / 低下(degraded)シグナルは確認上の可視化(review visibility)のためだけに扱います。",
  },
  overviewCards: [
    {
      label: "注意が必要なシグナル",
      value: "12",
      description: "確認用シグナルのみです。ガバナンス確認(governance review)用の静的 mock 件数です。",
      tone: "warning",
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "attention",
      visibility: "overview",
      readability: "scan_first",
      semanticBadges: [
        {
          id: "overview-review-signal",
          category: "review_signal",
          label: "確認用シグナルのみ",
          tone: "warning",
          visibility: "overview",
          semanticMeaning: "人による確認(human review)のためのシグナルであり、処理指示ではありません。",
        },
      ],
    },
    {
      label: "重大な注意確認",
      value: "3",
      description: "人が優先して確認するシグナルです。処理順や操作指示ではありません。",
      tone: "critical",
      severity: "critical",
      lifecycleState: "reviewing",
      degradationType: "attention",
      visibility: "overview",
      readability: "scan_first",
    },
    {
      label: "証跡の不足",
      value: "4",
      description: "監査確認(audit review)上の制限(limitation)です。証跡追加の指示ではありません。",
      tone: "warning",
      severity: "high",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "overview",
      readability: "short_note",
    },
    {
      label: "表示モード",
      value: "参照のみ",
      description: "実行なし(NO EXECUTION)。API 接続を行わない静的ダッシュボードです。",
      tone: "safe",
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "none",
      visibility: "overview",
      readability: "scan_first",
      semanticBadges: [
        {
          id: "overview-read-only",
          category: "read_only",
          label: "参照のみ",
          tone: "safe",
          visibility: "overview",
          semanticMeaning: "表示専用であり、変更(mutation)や実行(execution)を含みません。",
        },
      ],
    },
  ],
  incidentSummary: [
    {
      label: "未確認の要確認事項(incident)",
      value: "5",
      note: "調査と監査(audit)のための可視化です。source of truth の不具合確定を意味しません。",
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "semantic_safety",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:incident:unconfirmed-incident",
        projectionType: "incident",
        scope: "incident_summary",
        namespace: "governance.dashboard.incident",
        source: "static_mock",
        label: "未確認事項 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:incident:unconfirmed-incident",
        derivedFrom: ["governance:timeline:timeline-incident-001"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["要確認事項 source は確認用のまま表示"],
        signalLabels: ["要確認事項の表示モデルは確認用として表示"],
      }),
      incidentCategory: "investigation_signal",
      incidentSeverity: "watch",
      incidentStatus: "detected",
      incidentVisibility: "summary",
      relation: "requires_review",
      attentionLevel: "medium",
      projectionLabel: "調査表示モデル",
      groupKey: "unconfirmed-incident",
      groupLabel: "未確認の要確認事項",
      crossReferences: [
        {
          referenceId: "timeline-incident-001",
          projectionType: "timeline",
        label: "要確認事項の時系列表示モデル",
          relationType: "explains_context",
          semanticMeaning: "要確認事項(incident)シグナルの観測文脈を時系列(timeline)表示モデルとして参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-incident-investigation",
          projectionType: "incident",
          label: "調査境界",
          semanticBoundary: "調査上の可視化(visibility)境界であり、source of truth failure の確定ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-incident-unconfirmed",
          projectionType: "incident",
          label: "未確認事項の確認",
          attentionLevel: "medium",
          semanticMeaning: "人による確認(human review)の注意喚起であり、修正実行を意味しません。",
        },
      ],
    },
    {
      label: "ダッシュボード間の曖昧さ",
      value: "2",
      note: "監査文脈(audit context)として扱う前に意味確認(semantic review)が必要な可能性があります。",
      severity: "high",
      lifecycleState: "reviewing",
      degradationType: "meaning_consistency",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:incident:semantic-ambiguity",
        projectionType: "incident",
        scope: "incident_summary",
        namespace: "governance.dashboard.incident",
        source: "semantic_review",
        label: "意味曖昧さ identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:incident:semantic-ambiguity",
        derivedFrom: ["governance:timeline:timeline-semantic-001"],
        dependencies: ["governance:evidence:timeline-gap"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "degraded",
        issueLabels: ["意味境界に semantic review が必要"],
        signalLabels: ["意味曖昧さは確認上の注意度が高い"],
      }),
      incidentCategory: "semantic_ambiguity",
      incidentSeverity: "high",
      incidentStatus: "under_review",
      incidentVisibility: "attention",
      relation: "related_semantics",
      attentionLevel: "high",
      projectionLabel: "意味曖昧さ表示モデル",
      groupKey: "semantic-ambiguity",
      groupLabel: "意味曖昧さ",
      crossReferences: [
        {
          referenceId: "timeline-semantic-001",
          projectionType: "timeline",
          label: "意味確認の時系列",
          relationType: "shares_anchor",
          semanticMeaning: "意味一貫性(meaning consistency)の確認軸(anchor)を時系列(timeline)表示モデルと共有します。",
        },
        {
          referenceId: "timeline-gap",
          projectionType: "evidence",
          label: "時系列 gap 証跡",
          relationType: "supports_reasoning",
          semanticMeaning: "曖昧さの判断材料として証跡(evidence)表示モデルを参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-meaning-boundary",
          projectionType: "incident",
          label: "意味境界",
          semanticBoundary: "意味境界の確認であり、実行可能性(execution eligibility)の判定ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-semantic-ambiguity",
          projectionType: "incident",
          label: "意味曖昧さの注意確認",
          attentionLevel: "high",
          semanticMeaning: "意味一貫性確認(semantic consistency review)の優先表示であり、担当割当(assignment)ではありません。",
        },
      ],
    },
    {
      label: "滞留している確認シグナル",
      value: "3",
      note: "滞留は確認上の注意(review attention)のための情報です。correction や rebuild を開始しません。",
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "attention",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:incident:attention-backlog",
        projectionType: "incident",
        scope: "incident_summary",
        namespace: "governance.dashboard.incident",
        source: "policy_reference",
        label: "注意確認 backlog identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:incident:attention-backlog",
        dependencies: ["governance:operation:approval-reference"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["注意確認 backlog は表示されたまま"],
        signalLabels: ["注意確認表示モデルは参照のみとして分離"],
      }),
      incidentCategory: "attention_backlog",
      incidentSeverity: "watch",
      incidentStatus: "classified",
      incidentVisibility: "grouped",
      relation: "attention_marker",
      attentionLevel: "high",
      projectionLabel: "注意確認 backlog 表示モデル",
      groupKey: "attention-backlog",
      groupLabel: "注意確認 backlog",
      crossReferences: [
        {
          referenceId: "approval-reference",
          projectionType: "operation",
          label: "承認参照の表示モデル",
          relationType: "coordinates_review",
          semanticMeaning: "確認調整(review coordination)の文脈を参照しますが、approval mutation ではありません。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-attention-backlog",
          projectionType: "incident",
          label: "注意確認境界",
          semanticBoundary: "注意確認 backlog の可視化(visibility)であり、処理順序ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-review-backlog",
          projectionType: "incident",
          label: "backlog の注意確認",
          attentionLevel: "high",
          semanticMeaning: "見落とし防止のシグナルであり、retry や assignment を開始しません。",
        },
      ],
    },
  ],
  operationQueueSummary: [
    {
      label: "確認候補",
      value: "7",
      note: "候補は実行可能(executable-ready)ではなく、approval を意味しません。",
      severity: "info",
      lifecycleState: "detected",
      degradationType: "none",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:operation:review-candidate",
        projectionType: "operation",
        scope: "operation_queue",
        namespace: "governance.dashboard.operation",
        source: "static_mock",
        label: "確認候補 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:operation:review-candidate",
        dependencies: ["governance:incident:unconfirmed-incident"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "stable",
        signalLabels: ["確認候補は調整表示のみ"],
      }),
      operationCategory: "review_candidate",
      operationPriority: "normal",
      operationState: "visible",
      operationVisibility: "summary",
      relation: "review_coordination",
      projectionLabel: "確認調整の表示モデル",
      groupKey: "review-candidate",
      groupLabel: "確認候補",
      crossReferences: [
        {
          referenceId: "unconfirmed-incident",
          projectionType: "incident",
          label: "未確認事項の表示モデル",
          relationType: "coordinates_review",
          semanticMeaning: "確認候補(review candidate)と要確認事項(incident)の可視化(visibility)の関係を示します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-review-coordination",
          projectionType: "operation",
          label: "確認調整境界",
          semanticBoundary: "確認調整(review coordination)の表示であり、実行 queue ではありません。",
        },
      ],
      attentionSignals: [],
    },
    {
      label: "承認状態の参照",
      value: "2",
      note: "承認状態(approval state)はガバナンス参照として表示するだけです。",
      severity: "warning",
      lifecycleState: "reviewing",
      degradationType: "safe_interpretation",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:operation:approval-reference",
        projectionType: "operation",
        scope: "operation_queue",
        namespace: "governance.dashboard.operation",
        source: "policy_reference",
        label: "承認参照 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:operation:approval-reference",
        parentProjectionId: "governance:operation:review-candidate",
        dependencies: ["governance:incident:attention-backlog"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["承認参照は mutation と誤読される可能性あり"],
        signalLabels: ["承認境界は参照のみとして明示"],
      }),
      operationCategory: "approval_reference",
      operationPriority: "high",
      operationState: "review_reference",
      operationVisibility: "attention",
      relation: "approval_reference",
      projectionLabel: "承認参照の表示モデル",
      groupKey: "approval-reference",
      groupLabel: "承認参照",
      crossReferences: [
        {
          referenceId: "attention-backlog",
          projectionType: "incident",
          label: "注意確認 backlog 表示モデル",
          relationType: "bounds_policy",
          semanticMeaning: "承認参照(approval reference)の境界を要確認事項の注意確認(incident attention)と対応付けます。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-approval-boundary",
          projectionType: "operation",
          label: "承認境界",
          semanticBoundary: "承認状態(approval state)の参照であり、approval mutation ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-approval-reference",
          projectionType: "operation",
          label: "承認参照の注意確認",
          attentionLevel: "high",
          semanticMeaning: "approval 誤解を防ぐための確認シグナル(review signal)です。",
        },
      ],
      semanticBadges: [
        {
          id: "operation-approval-reference",
          category: "approval",
          label: "承認バッジ",
          tone: "warning",
          visibility: "summary",
          semanticMeaning: "approval mutation ではなく、approval state の参照表示です。",
        },
      ],
    },
    {
      label: "ライフサイクル(lifecycle)制限",
      value: "4",
      note: "ライフサイクル(lifecycle)ノートは操作 lifecycle の遷移ではありません。",
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "lifecycle",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:operation:lifecycle-limitation",
        projectionType: "operation",
        scope: "operation_queue",
        namespace: "governance.dashboard.operation",
        source: "policy_reference",
        label: "lifecycle 制限 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:operation:lifecycle-limitation",
        derivedFrom: ["governance:timeline:timeline-integrity-001"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["lifecycle 文言は境界確認が必要"],
        signalLabels: ["操作 lifecycle は確認文脈として表示"],
      }),
      operationCategory: "lifecycle_limitation",
      operationPriority: "high",
      operationState: "classified",
      operationVisibility: "grouped",
      relation: "lifecycle_context",
      projectionLabel: "ライフサイクル(lifecycle)確認表示モデル",
      groupKey: "lifecycle-limitation",
      groupLabel: "ライフサイクル(lifecycle)制限",
      crossReferences: [
        {
          referenceId: "timeline-integrity-001",
          projectionType: "timeline",
          label: "整合性時系列の表示モデル",
          relationType: "explains_context",
          semanticMeaning: "lifecycle limitation の確認文脈を時系列(timeline)表示モデルで参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-lifecycle-boundary",
          projectionType: "operation",
          label: "ライフサイクル(lifecycle)境界",
          semanticBoundary: "operation lifecycle 遷移ではなく、確認文脈(review context)の表示です。",
        },
      ],
      attentionSignals: [],
    },
  ],
  evidenceSummary: [
    {
      label: "証跡あり",
      value: "8",
      note: "確認(review)用の証跡が参照できます。正しさの保証ではありません。",
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "none",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:evidence:available-evidence",
        projectionType: "evidence",
        scope: "evidence_summary",
        namespace: "governance.dashboard.evidence",
        source: "lineage_policy",
        label: "証跡あり identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:evidence:available-evidence",
        dependencies: ["governance:operation:review-candidate"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "stable",
        signalLabels: ["証跡の由来(provenance)を表示"],
      }),
      evidenceCategory: "provenance",
      confidence: "high",
      evidenceVisibility: "summary",
      relation: "supports_reasoning",
      source: "static_mock",
      projectionLabel: "証跡説明表示モデル",
      groupKey: "available-evidence",
      groupLabel: "証跡あり",
      attention: false,
      crossReferences: [
        {
          referenceId: "review-candidate",
          projectionType: "operation",
          label: "確認候補の表示モデル",
          relationType: "supports_reasoning",
          semanticMeaning: "確認候補(review candidate)の判断材料として証跡の可視化(evidence visibility)を参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-provenance-lineage",
          projectionType: "evidence",
          label: "由来境界",
          semanticBoundary: "由来(provenance)の可視化であり、正しさの保証ではありません。",
        },
      ],
      attentionSignals: [],
      semanticBadges: [
        {
          id: "evidence-present-reference",
          category: "evidence",
          label: "証跡バッジ",
          tone: "info",
          visibility: "summary",
          semanticMeaning: "確認用 evidence の存在を示すだけで、正しさを保証しません。",
        },
      ],
    },
    {
      label: "証跡が部分的",
      value: "3",
      note: "部分的な証跡は監査上の制限(audit limitation)として見える状態を保ちます。",
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:evidence:partial-evidence",
        projectionType: "evidence",
        scope: "evidence_summary",
        namespace: "governance.dashboard.evidence",
        source: "lineage_policy",
        label: "部分証跡 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:evidence:partial-evidence",
        derivedFrom: ["governance:timeline:timeline-evidence-001"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["部分的な由来(lineage)が信頼度を制限"],
        signalLabels: ["部分的な証跡は境界付きで表示"],
      }),
      evidenceCategory: "lineage",
      confidence: "medium",
      evidenceVisibility: "lineage",
      relation: "marks_limitation",
      source: "semantic_review",
      projectionLabel: "部分的な由来表示モデル",
      groupKey: "partial-evidence",
      groupLabel: "部分的な証跡",
      attention: true,
      crossReferences: [
        {
          referenceId: "timeline-evidence-001",
          projectionType: "timeline",
          label: "証跡時系列の表示モデル",
          relationType: "shares_anchor",
          semanticMeaning: "部分的な証跡(partial evidence)の由来確認軸(lineage anchor)を時系列(timeline)と共有します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-partial-lineage",
          projectionType: "evidence",
          label: "部分的な由来境界",
          semanticBoundary: "由来制限(lineage limitation)の表示であり、証跡追加指示ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-partial-evidence",
          projectionType: "evidence",
          label: "部分証跡の注意確認",
          attentionLevel: "medium",
          semanticMeaning: "監査上の制限(audit limitation)の注意喚起であり、修復実行ではありません。",
        },
      ],
      semanticBadges: [
        {
          id: "evidence-partial-reference",
          category: "evidence",
          label: "証跡バッジ",
          tone: "warning",
          visibility: "summary",
          semanticMeaning: "部分的な証跡制限(evidence limitation)の表示であり、証跡追加指示ではありません。",
        },
      ],
    },
    {
      label: "時系列不足(gap)",
      value: "2",
      note: "時系列不足(timeline gap)は調査用シグナルです。replay eligibility ではありません。",
      severity: "high",
      lifecycleState: "reviewing",
      degradationType: "semantic_safety",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:evidence:timeline-gap",
        projectionType: "evidence",
        scope: "evidence_summary",
        namespace: "governance.dashboard.evidence",
        source: "semantic_review",
        label: "時系列 gap identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:evidence:timeline-gap",
        dependencies: ["governance:incident:semantic-ambiguity"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "degraded",
        issueLabels: ["時系列不足が説明信頼度を制限"],
        signalLabels: ["不足(gap)は監査文脈としてのみ表示"],
      }),
      evidenceCategory: "audit_context",
      confidence: "low",
      evidenceVisibility: "reasoning",
      relation: "qualifies_confidence",
      source: "timeline_projection",
      projectionLabel: "時系列不足(gap)説明表示モデル",
      groupKey: "timeline-gap",
      groupLabel: "時系列不足(gap)証跡",
      attention: true,
      crossReferences: [
        {
          referenceId: "semantic-ambiguity",
          projectionType: "incident",
          label: "意味曖昧さ表示モデル",
          relationType: "supports_reasoning",
          semanticMeaning: "時系列不足(timeline gap)を意味曖昧さ(semantic ambiguity)の説明文脈(reasoning context)として参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-timeline-gap",
          projectionType: "evidence",
          label: "時系列不足(gap)境界",
          semanticBoundary: "不足(gap)の可視化であり、replay eligibility ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-gap",
          projectionType: "evidence",
          label: "時系列不足(gap)注意確認",
          attentionLevel: "high",
          semanticMeaning: "確認上の注意(review attention)のためのシグナルであり、replay を開始しません。",
        },
      ],
    },
  ],
  readOnlyNotes: [
    {
      noteType: "semantic_safety",
      title: "意味安全(semantic safety)",
      category: "interpretation_safety",
      categoryLabel: "解釈安全",
      note: "説明信頼度 high は、確認(review)に必要な証跡や範囲(scope)が比較的そろっていることを示します。safe to execute ではありません。",
      severity: "warning",
      lifecycleState: "reviewing",
      degradationType: "semantic_safety",
      visibility: "note",
      readability: "detail_note",
    },
    {
      noteType: "integrity",
      title: "整合性確認",
      category: "governance_quality",
      categoryLabel: "ガバナンス品質",
      note: "整合性シグナル(integrity signal)はダッシュボード品質と監査上の制限(audit limitation)を示します。データを変更するものではありません。",
      severity: "info",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "note",
      readability: "detail_note",
    },
    {
      noteType: "attention",
      title: "注意確認品質",
      category: "review_signal_only",
      categoryLabel: "確認シグナルのみ",
      note: "確認優先度(priority)と注意確認(attention)は人による確認(human review)の見落とし防止に使います。execution priority や assignment mutation ではありません。",
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "attention",
      visibility: "note",
      readability: "detail_note",
    },
    {
      noteType: "safe_interpretation",
      title: "安全な解釈",
      category: "expectation_isolation",
      categoryLabel: "実行期待の分離",
      note: "参照のみ(READ ONLY)と実行なし(NO EXECUTION)は、この静的ダッシュボードの表示上の前提です。",
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "safe_interpretation",
      visibility: "note",
      readability: "detail_note",
    },
  ],
  timelineItems: [
    {
      identity: {
        projectionId: "governance:timeline:timeline-incident-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "static_mock",
        label: "要確認事項の時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-incident-001",
        dependencies: ["governance:incident:unconfirmed-incident"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["要確認事項の時系列は観測表示のみ"],
        signalLabels: ["要確認事項の時系列可視化には境界あり"],
      }),
      id: "timeline-incident-001",
      occurredAtLabel: "Mock day 1 09:00",
      category: "incident",
      categoryLabel: "要確認事項",
      title: "ガバナンス要確認シグナルを検知",
      description:
        "未確認の要確認事項(governance incident)を確認と観測(review / observability)用の時系列(timeline)に表示します。source of truth failure の確定ではありません。",
      sourceLabel: "静的 governance mock",
      projectionLabel: "ガバナンス event 表示モデル",
      timelineSeverity: "watch",
      timelineVisibility: "grouped",
      relation: "source_event",
      evidenceState: "referenced",
      groupKey: "incident",
      groupLabel: "要確認事項の表示モデル",
      highlight: false,
      attention: true,
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "semantic_safety",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "unconfirmed-incident",
          projectionType: "incident",
          label: "未確認事項の表示モデル",
          relationType: "explains_context",
          semanticMeaning: "時系列(timeline)上の観測を要確認事項の調査表示モデル(incident investigation projection)と接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-incident-investigation",
          projectionType: "timeline",
          label: "要確認事項の時系列 anchor",
          semanticBoundary: "時系列表示であり、source of truth failure の確定ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-incident",
          projectionType: "timeline",
          label: "要確認事項の時系列注意確認",
          attentionLevel: "medium",
          semanticMeaning: "時系列の可視化(timeline visibility)の注意喚起であり、対応開始ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-semantic-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "semantic_review",
        label: "意味確認の時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-semantic-001",
        dependencies: ["governance:incident:semantic-ambiguity"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "degraded",
        issueLabels: ["意味確認の時系列は意味一貫性 review が必要"],
        signalLabels: ["意味確認の時系列は確認用に強調表示"],
      }),
      id: "timeline-semantic-001",
      occurredAtLabel: "Mock day 1 10:30",
      category: "semantic_review",
      categoryLabel: "意味確認",
      title: "意味一貫性の確認メモ",
      description:
        "ダッシュボード間の意味一貫性(meaning consistency)を確認するための参照のみの時系列(timeline)項目です。",
      sourceLabel: "semantic governance mock",
      projectionLabel: "意味一貫性表示モデル",
      timelineSeverity: "attention",
      timelineVisibility: "highlighted",
      relation: "semantic_context",
      evidenceState: "lineage_visible",
      groupKey: "semantic",
      groupLabel: "意味確認表示モデル",
      highlight: true,
      attention: true,
      severity: "high",
      lifecycleState: "reviewing",
      degradationType: "meaning_consistency",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "semantic-ambiguity",
          projectionType: "incident",
          label: "意味曖昧さ表示モデル",
          relationType: "shares_anchor",
          semanticMeaning: "意味境界(meaning boundary)を要確認事項(incident)表示モデルと共有します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-meaning-boundary",
          projectionType: "timeline",
          label: "意味境界 anchor",
          semanticBoundary: "意味確認の確認軸(anchor)であり、execution 判断ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-semantic",
          projectionType: "timeline",
          label: "意味確認時系列の注意確認",
          attentionLevel: "high",
          semanticMeaning: "意味確認(semantic review)の可視化シグナル(visibility signal)であり、修正実行ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-evidence-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "lineage_policy",
        label: "証跡時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-evidence-001",
        dependencies: ["governance:evidence:partial-evidence"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["証跡時系列には部分的な由来(lineage)あり"],
        signalLabels: ["証跡制限は表示されたまま"],
      }),
      id: "timeline-evidence-001",
      occurredAtLabel: "Mock day 1 11:15",
      category: "evidence",
      categoryLabel: "証跡",
      title: "部分的な証跡制限を表示",
      description:
        "証跡が部分的であることを監査上の制限(audit limitation)として表示します。証跡追加の指示ではありません。",
      sourceLabel: "証跡サマリー mock",
      projectionLabel: "証跡由来表示モデル",
      timelineSeverity: "watch",
      timelineVisibility: "grouped",
      relation: "evidence_link",
      evidenceState: "partial",
      groupKey: "evidence",
      groupLabel: "証跡表示モデル",
      highlight: false,
      attention: true,
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "partial-evidence",
          projectionType: "evidence",
          label: "部分的な証跡表示モデル",
          relationType: "supports_reasoning",
          semanticMeaning: "時系列(timeline)上の証跡制限(limitation)を証跡(evidence)表示モデルと接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-partial-lineage",
          projectionType: "timeline",
          label: "証跡由来 anchor",
          semanticBoundary: "由来の可視化(lineage visibility)の確認軸(anchor)であり、証跡追加指示ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-evidence",
          projectionType: "timeline",
          label: "証跡時系列の注意確認",
          attentionLevel: "medium",
          semanticMeaning: "部分的な証跡(partial evidence)の注意表示であり、mutation ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-attention-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "policy_reference",
        label: "注意確認時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-attention-001",
        dependencies: ["governance:incident:attention-backlog"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["注意確認時系列は処理優先度と誤読される可能性あり"],
        signalLabels: ["注意確認は人による確認のみ"],
      }),
      id: "timeline-attention-001",
      occurredAtLabel: "Mock day 1 13:00",
      category: "attention",
      categoryLabel: "注意確認",
      title: "注意シグナルを表示",
      description:
        "注意確認(attention)は人による確認(human review)の見落とし防止のために表示します。処理順や操作指示ではありません。",
      sourceLabel: "注意確認品質 mock",
      projectionLabel: "注意確認表示モデル",
      timelineSeverity: "critical",
      timelineVisibility: "highlighted",
      relation: "attention_marker",
      evidenceState: "referenced",
      groupKey: "attention",
      groupLabel: "注意確認表示モデル",
      highlight: true,
      attention: true,
      severity: "critical",
      lifecycleState: "reviewing",
      degradationType: "attention",
      visibility: "detail",
      readability: "scan_first",
      crossReferences: [
        {
          referenceId: "attention-backlog",
          projectionType: "incident",
          label: "注意確認 backlog 表示モデル",
          relationType: "raises_attention",
          semanticMeaning: "注意シグナル(attention signal)を要確認事項の backlog(incident backlog)と接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-attention-backlog",
          projectionType: "timeline",
          label: "注意確認時系列 anchor",
          semanticBoundary: "人による確認上の注意(human review attention)の表示であり、処理順序ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-critical",
          projectionType: "timeline",
          label: "重大な時系列注意確認",
          attentionLevel: "urgent",
          semanticMeaning: "強い注意表示であり、assignment mutation ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-integrity-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "lineage_policy",
        label: "整合性時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-integrity-001",
        dependencies: ["governance:operation:lifecycle-limitation"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "stable",
        signalLabels: ["整合性の由来(lineage)を表示"],
      }),
      id: "timeline-integrity-001",
      occurredAtLabel: "Mock day 1 14:20",
      category: "integrity",
      categoryLabel: "整合性",
      title: "整合性制限を再確認",
      description:
        "整合性シグナル(integrity signal)はダッシュボード品質と監査上の制限(audit limitation)の表示です。データ変更を意味しません。",
      sourceLabel: "整合性確認 mock",
      projectionLabel: "整合性表示モデル",
      timelineSeverity: "info",
      timelineVisibility: "detail",
      relation: "derived_signal",
      evidenceState: "lineage_visible",
      groupKey: "integrity",
      groupLabel: "整合性表示モデル",
      highlight: false,
      attention: false,
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "integrity",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "lifecycle-limitation",
          projectionType: "operation",
          label: "ライフサイクル(lifecycle)確認表示モデル",
          relationType: "explains_context",
          semanticMeaning: "整合性(integrity)の文脈を操作 lifecycle limitation と接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-provenance-lineage",
          projectionType: "timeline",
          label: "整合性由来 anchor",
          semanticBoundary: "整合性由来(integrity lineage)の可視化(visibility)であり、データ変更ではありません。",
        },
      ],
      attentionSignals: [],
    },
  ],
};

// Read-only provider boundary. This can later be replaced by a read-only API
// adapter, but this phase intentionally returns static mock data only.
export function getGovernanceDashboardMockData(): GovernanceDashboardReadOnlyData {
  return governanceDashboardMockData;
}
