import type {
  GovernanceDashboardMockContract,
  GovernanceDashboardReadOnlyData,
  GovernanceProjectionIntegrity,
  GovernanceProjectionIntegrityLevel,
  GovernanceProjectionId,
  GovernanceProjectionLineage,
} from "./governanceDashboardTypes";

const parentTraceId = "mock-parent-trace-governance-dashboard";

function createGovernanceProjectionLineage({
  projectionId,
  parentProjectionId = "root",
  derivedFrom = [],
  dependencies = [],
}: {
  readonly projectionId: GovernanceProjectionId;
  readonly parentProjectionId?: GovernanceProjectionId | "root";
  readonly derivedFrom?: readonly GovernanceProjectionId[];
  readonly dependencies?: readonly GovernanceProjectionId[];
}): GovernanceProjectionLineage {
  return {
    parent: {
      parentProjectionId,
      label: parentProjectionId === "root" ? "root ガバナンス表示モデル" : "親表示モデル",
      semanticMeaning: "read-only lineage parent であり、projection 再生成や実行順序ではありません。",
    },
    derivedFrom: derivedFrom.map((sourceProjectionId) => ({
      sourceProjectionId,
      label: "由来となる説明 source",
      semanticMeaning: "reasoning context の由来であり、source mutation ではありません。",
    })),
    dependencies: dependencies.map((dependencyProjectionId) => ({
      dependencyProjectionId,
      label: "read-only 説明依存関係",
      semanticMeaning: "表示上の reasoning dependency であり、実行依存ではありません。",
    })),
    trace: {
      traceId: `${projectionId}:trace`,
      parentTraceId,
      requestChainLabel: "静的ガバナンス確認 parent trace",
    },
  };
}

function createGovernanceProjectionIntegrity({
  level,
  issueLabels = [],
  signalLabels = [],
}: {
  readonly level: GovernanceProjectionIntegrityLevel;
  readonly issueLabels?: readonly string[];
  readonly signalLabels?: readonly string[];
}): GovernanceProjectionIntegrity {
  return {
    level,
    issues: issueLabels.map((label, index) => ({
      issueId: `integrity-issue-${level}-${index + 1}`,
      level,
      label,
      semanticMeaning: "integrity review の表示であり、修復や再生成の開始ではありません。",
    })),
    signals: signalLabels.map((label, index) => ({
      signalId: `integrity-signal-${level}-${index + 1}`,
      level,
      label,
      semanticMeaning: "governance integrity の確認 signal であり、mutation を意味しません。",
    })),
    summaryLabel: `整合性: ${level}`,
  };
}

const governanceDashboardMockData: GovernanceDashboardMockContract = {
  renderingState: {
    renderState: "readonly",
    freshnessState: "fresh",
    degradationState: "limited",
    visibilityMode: "overview",
    label: "参照のみの描画状態",
    message:
      "static mock data を read-only rendering として表示しています。partial / degraded signal は review visibility のためだけに扱います。",
  },
  overviewCards: [
    {
      label: "注意が必要な signal",
      value: "12",
      description: "確認用シグナルのみです。ガバナンス review 用の静的 mock 件数です。",
      tone: "warning",
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "attention",
      visibility: "overview",
      readability: "scan_first",
      semanticBadges: [
        {
          id: "overview-review-signal",
          category: "review_signal",
          label: "確認用シグナルのみ",
          tone: "warning",
          visibility: "overview",
          semanticMeaning: "human review のための signal であり、処理指示ではありません。",
        },
      ],
    },
    {
      label: "重大な注意確認",
      value: "3",
      description: "人が優先して確認する signal です。処理順や操作指示ではありません。",
      tone: "critical",
      severity: "critical",
      lifecycleState: "reviewing",
      degradationType: "attention",
      visibility: "overview",
      readability: "scan_first",
    },
    {
      label: "証跡の不足",
      value: "4",
      description: "audit review 上の limitation です。証跡追加の指示ではありません。",
      tone: "warning",
      severity: "high",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "overview",
      readability: "short_note",
    },
    {
      label: "表示モード",
      value: "READ ONLY",
      description: "実行なし(NO EXECUTION)。API 接続を行わない静的 dashboard です。",
      tone: "safe",
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "none",
      visibility: "overview",
      readability: "scan_first",
      semanticBadges: [
        {
          id: "overview-read-only",
          category: "read_only",
          label: "参照のみ",
          tone: "safe",
          visibility: "overview",
          semanticMeaning: "表示専用であり、mutation や execution を含みません。",
        },
      ],
    },
  ],
  incidentSummary: [
    {
      label: "未確認の governance incident",
      value: "5",
      note: "調査と audit のための可視化です。source of truth の不具合確定を意味しません。",
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "semantic_safety",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:incident:unconfirmed-incident",
        projectionType: "incident",
        scope: "incident_summary",
        namespace: "governance.dashboard.incident",
        source: "static_mock",
        label: "未確認事項 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:incident:unconfirmed-incident",
        derivedFrom: ["governance:timeline:timeline-incident-001"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["incident source remains review-only"],
        signalLabels: ["incident projection is visible for review"],
      }),
      incidentCategory: "investigation_signal",
      incidentSeverity: "watch",
      incidentStatus: "detected",
      incidentVisibility: "summary",
      relation: "requires_review",
      attentionLevel: "medium",
      projectionLabel: "Investigation projection",
      groupKey: "unconfirmed-incident",
      groupLabel: "Unconfirmed incident",
      crossReferences: [
        {
          referenceId: "timeline-incident-001",
          projectionType: "timeline",
        label: "要確認事項の時系列表示モデル",
          relationType: "explains_context",
          semanticMeaning: "incident signal の観測文脈を timeline projection として参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-incident-investigation",
          projectionType: "incident",
          label: "調査境界",
          semanticBoundary: "調査 visibility の境界であり、source of truth failure の確定ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-incident-unconfirmed",
          projectionType: "incident",
          label: "未確認事項 review",
          attentionLevel: "medium",
          semanticMeaning: "human review の注意喚起であり、修正実行を意味しません。",
        },
      ],
    },
    {
      label: "Dashboard 間の曖昧さ",
      value: "2",
      note: "audit context として扱う前に semantic review が必要な可能性があります。",
      severity: "high",
      lifecycleState: "reviewing",
      degradationType: "meaning_consistency",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:incident:semantic-ambiguity",
        projectionType: "incident",
        scope: "incident_summary",
        namespace: "governance.dashboard.incident",
        source: "semantic_review",
        label: "意味曖昧さ identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:incident:semantic-ambiguity",
        derivedFrom: ["governance:timeline:timeline-semantic-001"],
        dependencies: ["governance:evidence:timeline-gap"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "degraded",
        issueLabels: ["meaning boundary requires semantic review"],
        signalLabels: ["semantic ambiguity has high review attention"],
      }),
      incidentCategory: "semantic_ambiguity",
      incidentSeverity: "high",
      incidentStatus: "under_review",
      incidentVisibility: "attention",
      relation: "related_semantics",
      attentionLevel: "high",
      projectionLabel: "意味曖昧さ表示モデル",
      groupKey: "semantic-ambiguity",
      groupLabel: "意味曖昧さ",
      crossReferences: [
        {
          referenceId: "timeline-semantic-001",
          projectionType: "timeline",
          label: "意味確認の時系列",
          relationType: "shares_anchor",
          semanticMeaning: "meaning consistency の anchor を timeline projection と共有します。",
        },
        {
          referenceId: "timeline-gap",
          projectionType: "evidence",
          label: "時系列 gap 証跡",
          relationType: "supports_reasoning",
          semanticMeaning: "曖昧さの判断材料として evidence projection を参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-meaning-boundary",
          projectionType: "incident",
          label: "意味境界",
          semanticBoundary: "意味境界の確認であり、execution eligibility の判定ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-semantic-ambiguity",
          projectionType: "incident",
          label: "意味曖昧さの注意確認",
          attentionLevel: "high",
          semanticMeaning: "semantic consistency review の優先表示であり、assignment ではありません。",
        },
      ],
    },
    {
      label: "滞留している確認シグナル",
      value: "3",
      note: "滞留は review attention のための情報です。correction や rebuild を開始しません。",
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "attention",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:incident:attention-backlog",
        projectionType: "incident",
        scope: "incident_summary",
        namespace: "governance.dashboard.incident",
        source: "policy_reference",
        label: "注意確認 backlog identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:incident:attention-backlog",
        dependencies: ["governance:operation:approval-reference"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["attention backlog remains visible"],
        signalLabels: ["attention projection is contained as read-only"],
      }),
      incidentCategory: "attention_backlog",
      incidentSeverity: "watch",
      incidentStatus: "classified",
      incidentVisibility: "grouped",
      relation: "attention_marker",
      attentionLevel: "high",
      projectionLabel: "注意確認 backlog 表示モデル",
      groupKey: "attention-backlog",
      groupLabel: "注意確認 backlog",
      crossReferences: [
        {
          referenceId: "approval-reference",
          projectionType: "operation",
          label: "Approval reference projection",
          relationType: "coordinates_review",
          semanticMeaning: "review coordination の文脈を参照しますが、approval mutation ではありません。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-attention-backlog",
          projectionType: "incident",
          label: "Attention boundary",
          semanticBoundary: "attention backlog の visibility であり、処理順序ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-review-backlog",
          projectionType: "incident",
          label: "Backlog attention",
          attentionLevel: "high",
          semanticMeaning: "見落とし防止の signal であり、retry や assignment を開始しません。",
        },
      ],
    },
  ],
  operationQueueSummary: [
    {
      label: "確認候補",
      value: "7",
      note: "候補は executable-ready ではなく、approval を意味しません。",
      severity: "info",
      lifecycleState: "detected",
      degradationType: "none",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:operation:review-candidate",
        projectionType: "operation",
        scope: "operation_queue",
        namespace: "governance.dashboard.operation",
        source: "static_mock",
        label: "確認候補 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:operation:review-candidate",
        dependencies: ["governance:incident:unconfirmed-incident"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "stable",
        signalLabels: ["review candidate remains coordination-only"],
      }),
      operationCategory: "review_candidate",
      operationPriority: "normal",
      operationState: "visible",
      operationVisibility: "summary",
      relation: "review_coordination",
      projectionLabel: "確認調整の表示モデル",
      groupKey: "review-candidate",
      groupLabel: "確認候補",
      crossReferences: [
        {
          referenceId: "unconfirmed-incident",
          projectionType: "incident",
          label: "未確認事項の表示モデル",
          relationType: "coordinates_review",
          semanticMeaning: "review candidate と incident visibility の関係を示します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-review-coordination",
          projectionType: "operation",
          label: "確認調整境界",
          semanticBoundary: "review coordination の表示であり、実行 queue ではありません。",
        },
      ],
      attentionSignals: [],
    },
    {
      label: "承認状態の参照",
      value: "2",
      note: "approval state は governance reference として表示するだけです。",
      severity: "warning",
      lifecycleState: "reviewing",
      degradationType: "safe_interpretation",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:operation:approval-reference",
        projectionType: "operation",
        scope: "operation_queue",
        namespace: "governance.dashboard.operation",
        source: "policy_reference",
        label: "承認参照 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:operation:approval-reference",
        parentProjectionId: "governance:operation:review-candidate",
        dependencies: ["governance:incident:attention-backlog"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["approval reference may be misread as mutation"],
        signalLabels: ["approval boundary is explicitly read-only"],
      }),
      operationCategory: "approval_reference",
      operationPriority: "high",
      operationState: "review_reference",
      operationVisibility: "attention",
      relation: "approval_reference",
      projectionLabel: "承認参照の表示モデル",
      groupKey: "approval-reference",
      groupLabel: "承認参照",
      crossReferences: [
        {
          referenceId: "attention-backlog",
          projectionType: "incident",
          label: "注意確認 backlog 表示モデル",
          relationType: "bounds_policy",
          semanticMeaning: "approval reference の境界を incident attention と対応付けます。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-approval-boundary",
          projectionType: "operation",
          label: "承認境界",
          semanticBoundary: "approval state の参照であり、approval mutation ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-approval-reference",
          projectionType: "operation",
          label: "承認参照の注意確認",
          attentionLevel: "high",
          semanticMeaning: "approval 誤解を防ぐための review signal です。",
        },
      ],
      semanticBadges: [
        {
          id: "operation-approval-reference",
          category: "approval",
          label: "承認 badge",
          tone: "warning",
          visibility: "summary",
          semanticMeaning: "approval mutation ではなく、approval state の参照表示です。",
        },
      ],
    },
    {
      label: "lifecycle 制限",
      value: "4",
      note: "lifecycle note は operation lifecycle の遷移ではありません。",
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "lifecycle",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:operation:lifecycle-limitation",
        projectionType: "operation",
        scope: "operation_queue",
        namespace: "governance.dashboard.operation",
        source: "policy_reference",
        label: "lifecycle 制限 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:operation:lifecycle-limitation",
        derivedFrom: ["governance:timeline:timeline-integrity-001"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["lifecycle wording needs boundary review"],
        signalLabels: ["operation lifecycle is shown as review context"],
      }),
      operationCategory: "lifecycle_limitation",
      operationPriority: "high",
      operationState: "classified",
      operationVisibility: "grouped",
      relation: "lifecycle_context",
      projectionLabel: "lifecycle 確認表示モデル",
      groupKey: "lifecycle-limitation",
      groupLabel: "lifecycle 制限",
      crossReferences: [
        {
          referenceId: "timeline-integrity-001",
          projectionType: "timeline",
          label: "整合性時系列の表示モデル",
          relationType: "explains_context",
          semanticMeaning: "lifecycle limitation の確認文脈を timeline projection で参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-lifecycle-boundary",
          projectionType: "operation",
          label: "lifecycle 境界",
          semanticBoundary: "operation lifecycle 遷移ではなく、review context の表示です。",
        },
      ],
      attentionSignals: [],
    },
  ],
  evidenceSummary: [
    {
      label: "証跡あり",
      value: "8",
      note: "review 用の証跡が参照できます。正しさの保証ではありません。",
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "none",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:evidence:available-evidence",
        projectionType: "evidence",
        scope: "evidence_summary",
        namespace: "governance.dashboard.evidence",
        source: "lineage_policy",
        label: "証跡あり identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:evidence:available-evidence",
        dependencies: ["governance:operation:review-candidate"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "stable",
        signalLabels: ["evidence provenance is visible"],
      }),
      evidenceCategory: "provenance",
      confidence: "high",
      evidenceVisibility: "summary",
      relation: "supports_reasoning",
      source: "static_mock",
      projectionLabel: "証跡説明表示モデル",
      groupKey: "available-evidence",
      groupLabel: "証跡あり",
      attention: false,
      crossReferences: [
        {
          referenceId: "review-candidate",
          projectionType: "operation",
          label: "確認候補の表示モデル",
          relationType: "supports_reasoning",
          semanticMeaning: "review candidate の判断材料として evidence visibility を参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-provenance-lineage",
          projectionType: "evidence",
          label: "由来境界",
          semanticBoundary: "provenance の可視化であり、正しさの保証ではありません。",
        },
      ],
      attentionSignals: [],
      semanticBadges: [
        {
          id: "evidence-present-reference",
          category: "evidence",
          label: "証跡 badge",
          tone: "info",
          visibility: "summary",
          semanticMeaning: "review 用 evidence の存在を示すだけで、正しさを保証しません。",
        },
      ],
    },
    {
      label: "証跡が部分的",
      value: "3",
      note: "部分的な証跡は audit limitation として見える状態を保ちます。",
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:evidence:partial-evidence",
        projectionType: "evidence",
        scope: "evidence_summary",
        namespace: "governance.dashboard.evidence",
        source: "lineage_policy",
        label: "部分証跡 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:evidence:partial-evidence",
        derivedFrom: ["governance:timeline:timeline-evidence-001"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["partial lineage limits confidence"],
        signalLabels: ["partial evidence remains explicitly bounded"],
      }),
      evidenceCategory: "lineage",
      confidence: "medium",
      evidenceVisibility: "lineage",
      relation: "marks_limitation",
      source: "semantic_review",
      projectionLabel: "部分的な由来表示モデル",
      groupKey: "partial-evidence",
      groupLabel: "部分的な証跡",
      attention: true,
      crossReferences: [
        {
          referenceId: "timeline-evidence-001",
          projectionType: "timeline",
          label: "証跡時系列の表示モデル",
          relationType: "shares_anchor",
          semanticMeaning: "partial evidence の lineage anchor を timeline と共有します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-partial-lineage",
          projectionType: "evidence",
          label: "部分的な由来境界",
          semanticBoundary: "lineage limitation の表示であり、証跡追加指示ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-partial-evidence",
          projectionType: "evidence",
          label: "部分証跡の注意確認",
          attentionLevel: "medium",
          semanticMeaning: "audit limitation の注意喚起であり、修復実行ではありません。",
        },
      ],
      semanticBadges: [
        {
          id: "evidence-partial-reference",
          category: "evidence",
          label: "証跡 badge",
          tone: "warning",
          visibility: "summary",
          semanticMeaning: "部分的な evidence limitation の表示であり、証跡追加指示ではありません。",
        },
      ],
    },
    {
      label: "時系列 gap",
      value: "2",
      note: "timeline gap は調査用 signal です。replay eligibility ではありません。",
      severity: "high",
      lifecycleState: "reviewing",
      degradationType: "semantic_safety",
      visibility: "summary",
      readability: "short_note",
      identity: {
        projectionId: "governance:evidence:timeline-gap",
        projectionType: "evidence",
        scope: "evidence_summary",
        namespace: "governance.dashboard.evidence",
        source: "semantic_review",
        label: "時系列 gap identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:evidence:timeline-gap",
        dependencies: ["governance:incident:semantic-ambiguity"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "degraded",
        issueLabels: ["timeline gap reduces reasoning confidence"],
        signalLabels: ["gap is visible as audit context only"],
      }),
      evidenceCategory: "audit_context",
      confidence: "low",
      evidenceVisibility: "reasoning",
      relation: "qualifies_confidence",
      source: "timeline_projection",
      projectionLabel: "時系列 gap 説明表示モデル",
      groupKey: "timeline-gap",
      groupLabel: "時系列 gap 証跡",
      attention: true,
      crossReferences: [
        {
          referenceId: "semantic-ambiguity",
          projectionType: "incident",
          label: "意味曖昧さ表示モデル",
          relationType: "supports_reasoning",
          semanticMeaning: "timeline gap を semantic ambiguity の reasoning context として参照します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-timeline-gap",
          projectionType: "evidence",
          label: "時系列 gap 境界",
          semanticBoundary: "gap の可視化であり、replay eligibility ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-gap",
          projectionType: "evidence",
          label: "時系列 gap 注意確認",
          attentionLevel: "high",
          semanticMeaning: "review attention のための signal であり、replay を開始しません。",
        },
      ],
    },
  ],
  readOnlyNotes: [
    {
      noteType: "semantic_safety",
      title: "意味安全(semantic safety)",
      category: "interpretation_safety",
      categoryLabel: "解釈安全",
      note: "Confidence high は、review に必要な証跡や scope が比較的そろっていることを示します。safe to execute ではありません。",
      severity: "warning",
      lifecycleState: "reviewing",
      degradationType: "semantic_safety",
      visibility: "note",
      readability: "detail_note",
    },
    {
      noteType: "integrity",
      title: "整合性確認",
      category: "governance_quality",
      categoryLabel: "ガバナンス品質",
      note: "Integrity signal は dashboard quality と audit limitation を示します。データを変更するものではありません。",
      severity: "info",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "note",
      readability: "detail_note",
    },
    {
      noteType: "attention",
      title: "注意確認品質",
      category: "review_signal_only",
      categoryLabel: "確認シグナルのみ",
      note: "priority と attention は human review の見落とし防止に使います。execution priority や assignment mutation ではありません。",
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "attention",
      visibility: "note",
      readability: "detail_note",
    },
    {
      noteType: "safe_interpretation",
      title: "安全な解釈",
      category: "expectation_isolation",
      categoryLabel: "実行期待の分離",
      note: "READ ONLY と NO EXECUTION は、この静的 dashboard の表示上の前提です。",
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "safe_interpretation",
      visibility: "note",
      readability: "detail_note",
    },
  ],
  timelineItems: [
    {
      identity: {
        projectionId: "governance:timeline:timeline-incident-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "static_mock",
        label: "要確認事項の時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-incident-001",
        dependencies: ["governance:incident:unconfirmed-incident"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["incident timeline is observational only"],
        signalLabels: ["timeline incident visibility is bounded"],
      }),
      id: "timeline-incident-001",
      occurredAtLabel: "Mock day 1 09:00",
      category: "incident",
      categoryLabel: "要確認事項",
      title: "ガバナンス要確認シグナルを検知",
      description:
        "未確認の governance incident を review / observability 用 timeline に表示します。source of truth failure の確定ではありません。",
      sourceLabel: "静的 governance mock",
      projectionLabel: "ガバナンス event 表示モデル",
      timelineSeverity: "watch",
      timelineVisibility: "grouped",
      relation: "source_event",
      evidenceState: "referenced",
      groupKey: "incident",
      groupLabel: "要確認事項の表示モデル",
      highlight: false,
      attention: true,
      severity: "warning",
      lifecycleState: "detected",
      degradationType: "semantic_safety",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "unconfirmed-incident",
          projectionType: "incident",
          label: "未確認事項の表示モデル",
          relationType: "explains_context",
          semanticMeaning: "timeline 上の観測を incident investigation projection と接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-incident-investigation",
          projectionType: "timeline",
          label: "要確認事項の時系列 anchor",
          semanticBoundary: "時系列表示であり、source of truth failure の確定ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-incident",
          projectionType: "timeline",
          label: "要確認事項の時系列注意確認",
          attentionLevel: "medium",
          semanticMeaning: "timeline visibility の注意喚起であり、対応開始ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-semantic-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "semantic_review",
        label: "意味確認の時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-semantic-001",
        dependencies: ["governance:incident:semantic-ambiguity"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "degraded",
        issueLabels: ["semantic timeline requires meaning consistency review"],
        signalLabels: ["semantic timeline is highlighted for review"],
      }),
      id: "timeline-semantic-001",
      occurredAtLabel: "Mock day 1 10:30",
      category: "semantic_review",
      categoryLabel: "意味確認",
      title: "意味一貫性の確認メモ",
      description:
        "Dashboard 間の meaning consistency を確認するための read-only timeline item です。",
      sourceLabel: "semantic governance mock",
      projectionLabel: "意味一貫性表示モデル",
      timelineSeverity: "attention",
      timelineVisibility: "highlighted",
      relation: "semantic_context",
      evidenceState: "lineage_visible",
      groupKey: "semantic",
      groupLabel: "意味確認表示モデル",
      highlight: true,
      attention: true,
      severity: "high",
      lifecycleState: "reviewing",
      degradationType: "meaning_consistency",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "semantic-ambiguity",
          projectionType: "incident",
          label: "意味曖昧さ表示モデル",
          relationType: "shares_anchor",
          semanticMeaning: "meaning boundary を incident projection と共有します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-meaning-boundary",
          projectionType: "timeline",
          label: "意味境界 anchor",
          semanticBoundary: "意味確認の anchor であり、execution 判断ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-semantic",
          projectionType: "timeline",
          label: "意味確認時系列の注意確認",
          attentionLevel: "high",
          semanticMeaning: "semantic review の visibility signal であり、修正実行ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-evidence-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "lineage_policy",
        label: "証跡時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-evidence-001",
        dependencies: ["governance:evidence:partial-evidence"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["evidence timeline has partial lineage"],
        signalLabels: ["evidence limitation remains visible"],
      }),
      id: "timeline-evidence-001",
      occurredAtLabel: "Mock day 1 11:15",
      category: "evidence",
      categoryLabel: "証跡",
      title: "部分的な証跡制限を表示",
      description:
        "証跡が部分的であることを audit limitation として表示します。証跡追加の指示ではありません。",
      sourceLabel: "証跡サマリー mock",
      projectionLabel: "証跡由来表示モデル",
      timelineSeverity: "watch",
      timelineVisibility: "grouped",
      relation: "evidence_link",
      evidenceState: "partial",
      groupKey: "evidence",
      groupLabel: "証跡表示モデル",
      highlight: false,
      attention: true,
      severity: "warning",
      lifecycleState: "classified",
      degradationType: "integrity",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "partial-evidence",
          projectionType: "evidence",
          label: "部分的な証跡表示モデル",
          relationType: "supports_reasoning",
          semanticMeaning: "timeline 上の証跡 limitation を evidence projection と接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-partial-lineage",
          projectionType: "timeline",
          label: "証跡由来 anchor",
          semanticBoundary: "lineage visibility の anchor であり、証跡追加指示ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-evidence",
          projectionType: "timeline",
          label: "証跡時系列の注意確認",
          attentionLevel: "medium",
          semanticMeaning: "partial evidence の注意表示であり、mutation ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-attention-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "policy_reference",
        label: "注意確認時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-attention-001",
        dependencies: ["governance:incident:attention-backlog"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "limited",
        issueLabels: ["attention timeline can be misread as priority"],
        signalLabels: ["attention remains human-review only"],
      }),
      id: "timeline-attention-001",
      occurredAtLabel: "Mock day 1 13:00",
      category: "attention",
      categoryLabel: "注意確認",
      title: "注意シグナルを表示",
      description:
        "attention は human review の見落とし防止のために表示します。処理順や操作指示ではありません。",
      sourceLabel: "注意確認品質 mock",
      projectionLabel: "注意確認表示モデル",
      timelineSeverity: "critical",
      timelineVisibility: "highlighted",
      relation: "attention_marker",
      evidenceState: "referenced",
      groupKey: "attention",
      groupLabel: "注意確認表示モデル",
      highlight: true,
      attention: true,
      severity: "critical",
      lifecycleState: "reviewing",
      degradationType: "attention",
      visibility: "detail",
      readability: "scan_first",
      crossReferences: [
        {
          referenceId: "attention-backlog",
          projectionType: "incident",
          label: "注意確認 backlog 表示モデル",
          relationType: "raises_attention",
          semanticMeaning: "attention signal を incident backlog と接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-attention-backlog",
          projectionType: "timeline",
          label: "注意確認時系列 anchor",
          semanticBoundary: "human review attention の表示であり、処理順序ではありません。",
        },
      ],
      attentionSignals: [
        {
          signalId: "attention-timeline-critical",
          projectionType: "timeline",
          label: "重大な時系列注意確認",
          attentionLevel: "urgent",
          semanticMeaning: "強い注意表示であり、assignment mutation ではありません。",
        },
      ],
    },
    {
      identity: {
        projectionId: "governance:timeline:timeline-integrity-001",
        projectionType: "timeline",
        scope: "timeline",
        namespace: "governance.dashboard.timeline",
        source: "lineage_policy",
        label: "整合性時系列 identity",
        parentTraceId: "mock-parent-trace-governance-dashboard",
      },
      lineage: createGovernanceProjectionLineage({
        projectionId: "governance:timeline:timeline-integrity-001",
        dependencies: ["governance:operation:lifecycle-limitation"],
      }),
      integrity: createGovernanceProjectionIntegrity({
        level: "stable",
        signalLabels: ["integrity lineage remains visible"],
      }),
      id: "timeline-integrity-001",
      occurredAtLabel: "Mock day 1 14:20",
      category: "integrity",
      categoryLabel: "整合性",
      title: "整合性制限を再確認",
      description:
        "integrity signal は dashboard quality と audit limitation の表示です。データ変更を意味しません。",
      sourceLabel: "整合性確認 mock",
      projectionLabel: "整合性表示モデル",
      timelineSeverity: "info",
      timelineVisibility: "detail",
      relation: "derived_signal",
      evidenceState: "lineage_visible",
      groupKey: "integrity",
      groupLabel: "整合性表示モデル",
      highlight: false,
      attention: false,
      severity: "info",
      lifecycleState: "reaffirmed",
      degradationType: "integrity",
      visibility: "detail",
      readability: "short_note",
      crossReferences: [
        {
          referenceId: "lifecycle-limitation",
          projectionType: "operation",
          label: "lifecycle 確認表示モデル",
          relationType: "explains_context",
          semanticMeaning: "integrity の文脈を operation lifecycle limitation と接続します。",
        },
      ],
      anchors: [
        {
          anchorId: "anchor-provenance-lineage",
          projectionType: "timeline",
          label: "整合性由来 anchor",
          semanticBoundary: "integrity lineage の visibility であり、データ変更ではありません。",
        },
      ],
      attentionSignals: [],
    },
  ],
};

// Read-only provider boundary. This can later be replaced by a read-only API
// adapter, but this phase intentionally returns static mock data only.
export function getGovernanceDashboardMockData(): GovernanceDashboardReadOnlyData {
  return governanceDashboardMockData;
}
