import type { InventoryIntegrityGraphData } from "./inventoryIntegrityGraphTypes";

export const inventoryIntegrityGraphMockData: InventoryIntegrityGraphData = {
  metadata: {
    title: "Inventory Integrity Graph",
    activeLayer: "Governance Layer",
    generatedAt: "mock-static",
    compareEndpointMethod: "GET",
    readOnlyBoundary: "Read Only / Observability Only / Mock Data",
    noExecutionMeaning:
      "This mock graph is display-only metadata and has no operation controls.",
  },
  summaries: [
    {
      id: "graph_health",
      title: "Graph Health",
      value: "Degraded",
      severity: "warning",
      description: "Graph health degraded by limited continuity signals.",
      relatedNodeId: "collapse_node",
      relatedPathId: "collapse_path",
    },
    {
      id: "graph_risk",
      title: "Graph Risk",
      value: "Elevated Risk",
      severity: "warning",
      description: "Risk is shown as observability metadata only.",
      relatedNodeId: "risk_node",
      relatedPathId: "collapse_path",
    },
    {
      id: "collapse",
      title: "Collapse",
      value: "Broken Continuity",
      severity: "critical",
      description: "Collapse summary is prioritized before positive signals.",
      relatedNodeId: "collapse_node",
      relatedPathId: "collapse_path",
    },
    {
      id: "convergence",
      title: "Convergence",
      value: "Partially Converged",
      severity: "neutral",
      description: "Positive direction remains subdued and contextual.",
      relatedNodeId: "convergence_node",
      relatedPathId: "convergence_path",
    },
    {
      id: "survivability",
      title: "Survivability",
      value: "Fragile",
      severity: "warning",
      description: "Long-term viability is readable with caveats.",
      relatedNodeId: "survivability_node",
      relatedPathId: "survivability_path",
    },
    {
      id: "sustainability",
      title: "Sustainability",
      value: "Conditional",
      severity: "neutral",
      description: "Persistence depends on support context.",
      relatedNodeId: "sustainability_node",
      relatedPathId: "sustainability_path",
    },
    {
      id: "maintainability",
      title: "Maintainability",
      value: "Conditional",
      severity: "neutral",
      description: "Maintenance capacity is not a maintenance workflow.",
      relatedNodeId: "maintainability_node",
      relatedPathId: "maintainability_path",
    },
    {
      id: "evolvability",
      title: "Evolvability",
      value: "Limited",
      severity: "neutral",
      description: "Future extension safety is not implementation permission.",
      relatedNodeId: "evolvability_node",
      relatedPathId: "evolvability_path",
    },
  ],
  nodes: [
    {
      id: "collapse_node",
      type: "collapse",
      label: "Broken Continuity",
      value: "broken_continuity",
      severity: "critical",
      reason: "continuity degraded",
      source: "mock",
      signals: ["continuity", "recoverability", "boundary"],
    },
    {
      id: "risk_node",
      type: "risk",
      label: "Elevated Risk",
      value: "elevated_risk",
      severity: "warning",
      reason: "collapse caveat raises graph risk",
      source: "mock",
      signals: ["collapse", "risk", "attention"],
    },
    {
      id: "convergence_node",
      type: "convergence",
      label: "Partial Convergence",
      value: "partially_converged",
      severity: "neutral",
      reason: "support signals remain limited",
      source: "mock",
      signals: ["confidence", "freshness", "evidence"],
    },
    {
      id: "survivability_node",
      type: "survivability",
      label: "Fragile Survivability",
      value: "fragile",
      severity: "warning",
      reason: "broken continuity limits long-term survivability",
      source: "mock",
      signals: ["degradation", "continuity", "survivability"],
    },
    {
      id: "sustainability_node",
      type: "sustainability",
      label: "Conditional Sustainability",
      value: "conditional",
      severity: "neutral",
      reason: "persistence depends on support context",
      source: "mock",
      signals: ["persistence", "support", "lifecycle"],
    },
    {
      id: "maintainability_node",
      type: "maintainability",
      label: "Conditional Maintainability",
      value: "conditional",
      severity: "neutral",
      reason: "sustainability context remains conditional",
      source: "mock",
      signals: ["sustainability", "support", "traceability"],
    },
    {
      id: "evolvability_node",
      type: "evolvability",
      label: "Limited Evolvability",
      value: "limited",
      severity: "neutral",
      reason: "maintainability context is conditional",
      source: "mock",
      signals: ["maintainability", "support", "future extension"],
    },
  ],
  edges: [
    {
      id: "edge_collapse_to_risk",
      from: "collapse_node",
      to: "risk_node",
      type: "collapse_propagation",
      label: "Collapse to Risk",
      description: "collapse propagation raises graph risk",
      severity: "critical",
    },
    {
      id: "edge_collapse_to_convergence",
      from: "collapse_node",
      to: "convergence_node",
      type: "collapse_caveat",
      label: "Collapse caveat to convergence",
      description: "collapse context limits positive interpretation",
      severity: "warning",
    },
    {
      id: "edge_survivability_to_sustainability",
      from: "survivability_node",
      to: "sustainability_node",
      type: "survivability_propagation",
      label: "Survivability to Sustainability",
      description: "survivability caveat constrains long-term persistence",
      severity: "warning",
    },
    {
      id: "edge_sustainability_to_maintainability",
      from: "sustainability_node",
      to: "maintainability_node",
      type: "maintainability_propagation",
      label: "Sustainability to Maintainability",
      description: "sustainability context constrains maintenance capacity",
      severity: "neutral",
    },
    {
      id: "edge_maintainability_to_evolvability",
      from: "maintainability_node",
      to: "evolvability_node",
      type: "evolvability_propagation",
      label: "Maintainability to Evolvability",
      description: "future extension remains bounded by support context",
      severity: "neutral",
    },
  ],
  viewModes: [
    { id: "overview", label: "Overview" },
    { id: "collapse", label: "Collapse" },
    { id: "convergence", label: "Convergence" },
    { id: "survivability", label: "Survivability" },
    { id: "sustainability", label: "Sustainability" },
    { id: "maintainability", label: "Maintainability" },
    { id: "evolvability", label: "Evolvability" },
  ],
  defaultSummaryId: "collapse",
  defaultNodeId: "collapse_node",
  defaultEdgeId: "edge_collapse_to_risk",
  defaultHighlightedPathId: "collapse_path",
};
