import type { InventoryIntegrityGraphData } from "./inventoryIntegrityGraphTypes";

export const inventoryIntegrityGraphMockData: InventoryIntegrityGraphData = {
  metadata: {
    title: "Inventory Integrity Graph",
    activeLayer: "ガバナンス層 / Governance Layer",
    generatedAt: "mock-static",
    compareEndpointMethod: "GET",
    readOnlyBoundary:
      "Read Only / 読み取り専用, Observability Only / 観測専用, Mock Data / モックデータ",
    noExecutionMeaning:
      "表示専用のメタデータです。No Execution Controls / 実行操作なし。",
  },
  summaries: [
    {
      id: "graph_health",
      title: "グラフ健全性 / Graph Health",
      value: "制限あり / Degraded",
      severity: "warning",
      description:
        "継続性シグナルに制限があるため、健全性は注意して参照します。",
      relatedNodeId: "collapse_node",
      relatedPathId: "collapse_path",
    },
    {
      id: "graph_risk",
      title: "グラフリスク / Graph Risk",
      value: "高め / Elevated Risk",
      severity: "warning",
      description: "リスクは観測用メタデータとしてのみ表示します。",
      relatedNodeId: "risk_node",
      relatedPathId: "collapse_path",
    },
    {
      id: "collapse",
      title: "崩壊傾向 / Collapse",
      value: "継続性低下 / Broken Continuity",
      severity: "critical",
      description: "positive signal より先に崩壊傾向を確認します。",
      relatedNodeId: "collapse_node",
      relatedPathId: "collapse_path",
    },
    {
      id: "convergence",
      title: "収束傾向 / Convergence",
      value: "部分収束 / Partially Converged",
      severity: "neutral",
      description: "収束方向は補足情報として控えめに表示します。",
      relatedNodeId: "convergence_node",
      relatedPathId: "convergence_path",
    },
    {
      id: "survivability",
      title: "生存性 / Survivability",
      value: "脆弱 / Fragile",
      severity: "warning",
      description: "長期的な読み取り可能性には注意点があります。",
      relatedNodeId: "survivability_node",
      relatedPathId: "survivability_path",
    },
    {
      id: "sustainability",
      title: "持続性 / Sustainability",
      value: "条件付き / Conditional",
      severity: "neutral",
      description: "持続性は support context と合わせて参照します。",
      relatedNodeId: "sustainability_node",
      relatedPathId: "sustainability_path",
    },
    {
      id: "maintainability",
      title: "保守性 / Maintainability",
      value: "条件付き / Conditional",
      severity: "neutral",
      description: "保守性は維持しやすさの観測であり、作業指示ではありません。",
      relatedNodeId: "maintainability_node",
      relatedPathId: "maintainability_path",
    },
    {
      id: "evolvability",
      title: "発展性 / Evolvability",
      value: "限定的 / Limited",
      severity: "neutral",
      description: "将来拡張の読みやすさであり、実装許可ではありません。",
      relatedNodeId: "evolvability_node",
      relatedPathId: "evolvability_path",
    },
  ],
  nodes: [
    {
      id: "collapse_node",
      type: "collapse",
      label: "継続性低下 / Broken Continuity",
      value: "broken_continuity",
      severity: "critical",
      reason: "continuity が degraded と読める mock signal です。",
      source: "mock / モック",
      signals: ["continuity", "recoverability", "boundary"],
    },
    {
      id: "risk_node",
      type: "risk",
      label: "高めのリスク / Elevated Risk",
      value: "elevated_risk",
      severity: "warning",
      reason: "collapse caveat が graph risk を高める読み方です。",
      source: "mock / モック",
      signals: ["collapse", "risk", "attention"],
    },
    {
      id: "convergence_node",
      type: "convergence",
      label: "部分収束 / Partial Convergence",
      value: "partially_converged",
      severity: "neutral",
      reason: "support signals が限定的なため、収束は補足として参照します。",
      source: "mock / モック",
      signals: ["confidence", "freshness", "evidence"],
    },
    {
      id: "survivability_node",
      type: "survivability",
      label: "脆弱な生存性 / Fragile Survivability",
      value: "fragile",
      severity: "warning",
      reason: "継続性低下が long-term survivability を制限する読み方です。",
      source: "mock / モック",
      signals: ["degradation", "continuity", "survivability"],
    },
    {
      id: "sustainability_node",
      type: "sustainability",
      label: "条件付き持続性 / Conditional Sustainability",
      value: "conditional",
      severity: "neutral",
      reason: "持続性は support context に依存して参照します。",
      source: "mock / モック",
      signals: ["persistence", "support", "lifecycle"],
    },
    {
      id: "maintainability_node",
      type: "maintainability",
      label: "条件付き保守性 / Conditional Maintainability",
      value: "conditional",
      severity: "neutral",
      reason: "sustainability context が条件付きのため、保守性も補足として参照します。",
      source: "mock / モック",
      signals: ["sustainability", "support", "traceability"],
    },
    {
      id: "evolvability_node",
      type: "evolvability",
      label: "限定的な発展性 / Limited Evolvability",
      value: "limited",
      severity: "neutral",
      reason: "maintainability context が条件付きのため、発展性は限定的です。",
      source: "mock / モック",
      signals: ["maintainability", "support", "future extension"],
    },
  ],
  edges: [
    {
      id: "edge_collapse_to_risk",
      from: "collapse_node",
      to: "risk_node",
      type: "collapse_propagation",
      label: "崩壊傾向からリスク / Collapse to Risk",
      description: "collapse propagation が graph risk を高める観測上の関係です。",
      severity: "critical",
    },
    {
      id: "edge_collapse_to_convergence",
      from: "collapse_node",
      to: "convergence_node",
      type: "collapse_caveat",
      label: "崩壊傾向の注意点 / Collapse caveat to convergence",
      description: "collapse context が positive interpretation を制限します。",
      severity: "warning",
    },
    {
      id: "edge_survivability_to_sustainability",
      from: "survivability_node",
      to: "sustainability_node",
      type: "survivability_propagation",
      label: "生存性から持続性 / Survivability to Sustainability",
      description: "survivability caveat が long-term persistence を制限します。",
      severity: "warning",
    },
    {
      id: "edge_sustainability_to_maintainability",
      from: "sustainability_node",
      to: "maintainability_node",
      type: "maintainability_propagation",
      label: "持続性から保守性 / Sustainability to Maintainability",
      description: "sustainability context が maintenance capacity を制限します。",
      severity: "neutral",
    },
    {
      id: "edge_maintainability_to_evolvability",
      from: "maintainability_node",
      to: "evolvability_node",
      type: "evolvability_propagation",
      label: "保守性から発展性 / Maintainability to Evolvability",
      description: "future extension は support context の範囲で参照します。",
      severity: "neutral",
    },
  ],
  viewModes: [
    { id: "overview", label: "概要 / Overview" },
    { id: "collapse", label: "崩壊傾向 / Collapse" },
    { id: "convergence", label: "収束傾向 / Convergence" },
    { id: "survivability", label: "生存性 / Survivability" },
    { id: "sustainability", label: "持続性 / Sustainability" },
    { id: "maintainability", label: "保守性 / Maintainability" },
    { id: "evolvability", label: "発展性 / Evolvability" },
  ],
  defaultSummaryId: "collapse",
  defaultNodeId: "collapse_node",
  defaultEdgeId: "edge_collapse_to_risk",
  defaultHighlightedPathId: "collapse_path",
};
